name: Release

on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm64]
        include:
          - goos: windows
            goarch: amd64
            goamd64: v3
          - goos: linux
            goarch: amd64
            goamd64: v3
          - goos: darwin
            goarch: amd64
            goamd64: v3
          - goos: windows
            goarch: amd64
            goamd64: v1
          - goos: linux
            goarch: amd64
            goamd64: v1
          - goos: darwin
            goarch: amd64
            goamd64: v1
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: amd64
            goos: linux
          - goarch: amd64
            goos: darwin
          - goarch: amd64
            goos: windows

    steps:
      - uses: actions/checkout@v3

      - uses: Zxilly/go-release-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goamd64: ${{ matrix.goamd64 }}
          extra_files: LICENSE README.md